WIP: Find posts by more than one keyword
OpenEugene/openboard pull request #143
Opened 2021-03-12 06:24 UTC by xipxape

Closes #141

2021-03-12 06:25 UTC, appins commented
I still need to write tests and we should probably talk about how keywords are actually being used.

2021-03-12 06:26 UTC, appins commented on back/internal/postsvc/internal/postdb/qrypost.go
> +	like := strings.Join(x.Keywords, " ")
Because I don't think that it was intended that they would just be joined together.

2021-03-13 00:46 UTC, codegold79 commented
I haven't read through the changes carefully, but I wanted to write something here so we don't miss talking about it. Should we limit the number of keywords a person sends to the search? They could purposely overload our database by sending in a novel into the search box, couldn't they?

2021-03-13 01:57 UTC, appins commented
> I haven't read through the changes carefully, but I wanted to write something here so we don't miss talking about it. Should we limit the number of keywords a person sends to the search? They could purposely overload our database by sending in a novel into the search box, couldn't they?

@codegold79 Sure. I don't know how big of an issue that could be, but I know Google, for example, only allows searching by the first 30-something words. I'm not sure, however, where we would put that logic. We could put a filter here, but I feel like that belongs somewhere else in the code. I'm not sure, I'm new to this base. 

Also, we may want to limit the number of results a person gets back. I know @coatsd was working on that in another branch, but I'm not sure when/if those changes will be live.

2021-03-24 02:19 UTC, daved requested changes

2021-03-24 02:19 UTC, daved commented on back/internal/postsvc/internal/postdb/mysql/0003_add_fulltext_columns.sql
> +-- +migrate Up
I'd prefer it if the filename was "0003_add_post_fulltext_cols.sql".

2021-03-24 02:32 UTC, daved requested changes

2021-03-24 02:32 UTC, daved commented on back/tests/openbsrv/postsvc_test.go
> +		}{
I'm not sure if we've been following this practice consistently so far... I suggest adding a field for the name of the test. The name is useful to filter for specific tests (when tests are eventually organized to be run independently), and it also documents the nature/intent of the test. For myself, thinking about the nature/name of a test case often brings to mind other test cases that would make sense to nail down.

2021-03-24 02:55 UTC, daved approved these changes

2021-03-24 02:56 UTC, codegold79 approved these changes
LGTM

2021-03-24 02:56 UTC, merged